### ISSUE TITLE
Variables doesn't work in btnmatrix

### ISSUE THREAD

**Issue by Asbjoern** [markusressel/openhasp-config-manager#9]
Variables does not expand to the value in global.vars.yaml if used in a btnmatrix.
e.g.:
```
{"page":1,"id":2,"obj":"btnmatrix","options":["{{ stuestates.s0 }}","{{ stuestates.s1 }}","{{ stuestates.s3 }}", ...
```

**Comment by markusressel** [comment]
This is probably caused by the fact that the value is a list and you are using templates within list items.
I have not implemented this usecase yet, but its a good feature to have.

**Comment by markusressel** [comment]
Should work now, please give it a try :nerd_face:
